### ISSUE TITLE
Cannot install or use on macOS High Sierra

### ISSUE THREAD

**Issue by pvaibhav** [sintaxi/harp#632]
On macOS 10.13.4 with latest xcode.
Followed instructions:

```
brew install node
npm install -g harp
```

First fails because python2 is not installed. Can be fixed by `brew install python2`

Then it fails during some C++ compilation:
```
In file included from ../src/binding.cpp:3:
../src/sass_context_wrapper.h:8:10: fatal error: 'sass/context.h' file not found
#include <sass/context.h>
         ^~~~~~~~~~~~~~~~
```

Problems: `libsass` and `python2` not listed as a dependency.

After doing `brew install libsass`, harp can be compiled and installed, but doesn't work:

```
~/Work/harp                                                                           
▶ harp
dyld: lazy symbol binding failed: Symbol not found: _sass_make_boolean
  Referenced from: /usr/local/lib/node_modules/harp/node_modules/node-sass/vendor/darwin-x64-64/binding.node
  Expected in: flat namespace

dyld: Symbol not found: _sass_make_boolean
  Referenced from: /usr/local/lib/node_modules/harp/node_modules/node-sass/vendor/darwin-x64-64/binding.node
  Expected in: flat namespace

[1]    78997 abort      harp

```

How do I make this work? Thanks.

**Comment by pvaibhav** [comment]
The reason is that `node-sass` version must be at least v4.9.0 to work with node 10.1.0.

Please update your dependencies. This was too much unnecessary work learning how nodejs and npm works, before I managed to make a temporary fix by editing the package-lock.json file manually. Specially when the first sentence of the quick start guide says 

> First, install Node.js. Harp uses Node.js, but you don’t need to know about Node.js or even JavaScript to use Harp.

**Comment by ad-si** [comment]
I'm getting this error:

```
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)
```
Probably has the same root cause

**Comment by sintaxi** [comment]
@ad-si I just released `v.0.26.0` about an hour ago. Is that what you we're installing?

**Comment by ad-si** [comment]
@sintaxi Yes it is

**Comment by sintaxi** [comment]
@ad-si Are you able to install `npm install harp@0.25.0`? Also what version of surge are you using?

**Comment by ad-si** [comment]
Yeah, that's what I did. I downgraded to harp@0.25.0 and then it worked. (Btw: I'm still using node v8.11.1)

**Comment by misterhtmlcss** [comment]
This conversation looks like the issue has been resolved, so I'm going to close it. Thank you for choosing Harp @ad-si and let us know if you have further issues in the future.

**Comment by kenjura** [comment]
Same issue, using High Sierra 10.13.6, node 11.0.0. I tried current version of Harp, then tried @ad-si's approach and installed 0.25.0. It didn't help.

**Comment by misterhtmlcss** [comment]
hi @kenjura currently we support only the LTS versions of node. We are aware that Node 10 recently went LTS, but we aren't there yet. The best short-term advice I could give you are to go the NVM route; it's what I use as I develop on multiple versions of NodeJS. Do you know NVM?
In case you don't and are looking for more help; check these out:

- [NVM tutorial MacOS/Linux info only](https://nodesource.com/blog/installing-node-js-tutorial-using-nvm-on-mac-os-x-and-ubuntu/)
- [NVM tutorial](https://www.keycdn.com/blog/node-version-manager)

Let me know if this is something you are willing to pursue. I personally resisted it for a long time, but found that NVM was really something that made life easier and wasn't actually much of a time or intellectual investment.

Looking forward to hearing how it goes Ken.

**Comment by kenjura** [comment]
Okay, that makes sense. I suppose it's reasonable, given that it's still version 0, and 11 is kind of bleeding edge. I switched to 8.12 and it seems to be working fine. Thanks!
